package ProtoBufProtos;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Environment.proto

public final class EnvironmentProtos {
  private EnvironmentProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WaterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Water)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string uniqueObjectName = 1;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    boolean hasUniqueObjectName();
    /**
     * <code>required string uniqueObjectName = 1;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    java.lang.String getUniqueObjectName();
    /**
     * <code>required string uniqueObjectName = 1;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    com.google.protobuf.ByteString
        getUniqueObjectNameBytes();

    /**
     * <code>required float posX = 2;</code>
     */
    boolean hasPosX();
    /**
     * <code>required float posX = 2;</code>
     */
    float getPosX();

    /**
     * <code>required float posY = 3;</code>
     */
    boolean hasPosY();
    /**
     * <code>required float posY = 3;</code>
     */
    float getPosY();

    /**
     * <code>required float scaleX = 4;</code>
     */
    boolean hasScaleX();
    /**
     * <code>required float scaleX = 4;</code>
     */
    float getScaleX();

    /**
     * <code>required float scaleY = 5;</code>
     */
    boolean hasScaleY();
    /**
     * <code>required float scaleY = 5;</code>
     */
    float getScaleY();
  }
  /**
   * Protobuf type {@code Water}
   */
  public static final class Water extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Water)
      WaterOrBuilder {
    // Use Water.newBuilder() to construct.
    private Water(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Water(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Water defaultInstance;
    public static Water getDefaultInstance() {
      return defaultInstance;
    }

    public Water getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Water(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              uniqueObjectName_ = bs;
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              posX_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              posY_ = input.readFloat();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              scaleX_ = input.readFloat();
              break;
            }
            case 45: {
              bitField0_ |= 0x00000010;
              scaleY_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EnvironmentProtos.internal_static_Water_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EnvironmentProtos.internal_static_Water_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EnvironmentProtos.Water.class, EnvironmentProtos.Water.Builder.class);
    }

    public static com.google.protobuf.Parser<Water> PARSER =
        new com.google.protobuf.AbstractParser<Water>() {
      public Water parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Water(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Water> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int UNIQUEOBJECTNAME_FIELD_NUMBER = 1;
    private java.lang.Object uniqueObjectName_;
    /**
     * <code>required string uniqueObjectName = 1;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    public boolean hasUniqueObjectName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string uniqueObjectName = 1;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    public java.lang.String getUniqueObjectName() {
      java.lang.Object ref = uniqueObjectName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uniqueObjectName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string uniqueObjectName = 1;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUniqueObjectNameBytes() {
      java.lang.Object ref = uniqueObjectName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uniqueObjectName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POSX_FIELD_NUMBER = 2;
    private float posX_;
    /**
     * <code>required float posX = 2;</code>
     */
    public boolean hasPosX() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required float posX = 2;</code>
     */
    public float getPosX() {
      return posX_;
    }

    public static final int POSY_FIELD_NUMBER = 3;
    private float posY_;
    /**
     * <code>required float posY = 3;</code>
     */
    public boolean hasPosY() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required float posY = 3;</code>
     */
    public float getPosY() {
      return posY_;
    }

    public static final int SCALEX_FIELD_NUMBER = 4;
    private float scaleX_;
    /**
     * <code>required float scaleX = 4;</code>
     */
    public boolean hasScaleX() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required float scaleX = 4;</code>
     */
    public float getScaleX() {
      return scaleX_;
    }

    public static final int SCALEY_FIELD_NUMBER = 5;
    private float scaleY_;
    /**
     * <code>required float scaleY = 5;</code>
     */
    public boolean hasScaleY() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required float scaleY = 5;</code>
     */
    public float getScaleY() {
      return scaleY_;
    }

    private void initFields() {
      uniqueObjectName_ = "";
      posX_ = 0F;
      posY_ = 0F;
      scaleX_ = 0F;
      scaleY_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUniqueObjectName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPosX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPosY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasScaleX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasScaleY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUniqueObjectNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, posX_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, posY_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, scaleX_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeFloat(5, scaleY_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUniqueObjectNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, posX_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, posY_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, scaleX_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, scaleY_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static EnvironmentProtos.Water parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EnvironmentProtos.Water parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EnvironmentProtos.Water parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EnvironmentProtos.Water parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EnvironmentProtos.Water parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static EnvironmentProtos.Water parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static EnvironmentProtos.Water parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static EnvironmentProtos.Water parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static EnvironmentProtos.Water parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static EnvironmentProtos.Water parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(EnvironmentProtos.Water prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Water}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Water)
        EnvironmentProtos.WaterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EnvironmentProtos.internal_static_Water_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EnvironmentProtos.internal_static_Water_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EnvironmentProtos.Water.class, EnvironmentProtos.Water.Builder.class);
      }

      // Construct using EnvironmentProtos.Water.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uniqueObjectName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        posX_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        posY_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        scaleX_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        scaleY_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EnvironmentProtos.internal_static_Water_descriptor;
      }

      public EnvironmentProtos.Water getDefaultInstanceForType() {
        return EnvironmentProtos.Water.getDefaultInstance();
      }

      public EnvironmentProtos.Water build() {
        EnvironmentProtos.Water result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public EnvironmentProtos.Water buildPartial() {
        EnvironmentProtos.Water result = new EnvironmentProtos.Water(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uniqueObjectName_ = uniqueObjectName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.posX_ = posX_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.posY_ = posY_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.scaleX_ = scaleX_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.scaleY_ = scaleY_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EnvironmentProtos.Water) {
          return mergeFrom((EnvironmentProtos.Water)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EnvironmentProtos.Water other) {
        if (other == EnvironmentProtos.Water.getDefaultInstance()) return this;
        if (other.hasUniqueObjectName()) {
          bitField0_ |= 0x00000001;
          uniqueObjectName_ = other.uniqueObjectName_;
          onChanged();
        }
        if (other.hasPosX()) {
          setPosX(other.getPosX());
        }
        if (other.hasPosY()) {
          setPosY(other.getPosY());
        }
        if (other.hasScaleX()) {
          setScaleX(other.getScaleX());
        }
        if (other.hasScaleY()) {
          setScaleY(other.getScaleY());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUniqueObjectName()) {
          
          return false;
        }
        if (!hasPosX()) {
          
          return false;
        }
        if (!hasPosY()) {
          
          return false;
        }
        if (!hasScaleX()) {
          
          return false;
        }
        if (!hasScaleY()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        EnvironmentProtos.Water parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (EnvironmentProtos.Water) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object uniqueObjectName_ = "";
      /**
       * <code>required string uniqueObjectName = 1;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public boolean hasUniqueObjectName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string uniqueObjectName = 1;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public java.lang.String getUniqueObjectName() {
        java.lang.Object ref = uniqueObjectName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uniqueObjectName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string uniqueObjectName = 1;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUniqueObjectNameBytes() {
        java.lang.Object ref = uniqueObjectName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uniqueObjectName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string uniqueObjectName = 1;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public Builder setUniqueObjectName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uniqueObjectName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string uniqueObjectName = 1;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public Builder clearUniqueObjectName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uniqueObjectName_ = getDefaultInstance().getUniqueObjectName();
        onChanged();
        return this;
      }
      /**
       * <code>required string uniqueObjectName = 1;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public Builder setUniqueObjectNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uniqueObjectName_ = value;
        onChanged();
        return this;
      }

      private float posX_ ;
      /**
       * <code>required float posX = 2;</code>
       */
      public boolean hasPosX() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float posX = 2;</code>
       */
      public float getPosX() {
        return posX_;
      }
      /**
       * <code>required float posX = 2;</code>
       */
      public Builder setPosX(float value) {
        bitField0_ |= 0x00000002;
        posX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float posX = 2;</code>
       */
      public Builder clearPosX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        posX_ = 0F;
        onChanged();
        return this;
      }

      private float posY_ ;
      /**
       * <code>required float posY = 3;</code>
       */
      public boolean hasPosY() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required float posY = 3;</code>
       */
      public float getPosY() {
        return posY_;
      }
      /**
       * <code>required float posY = 3;</code>
       */
      public Builder setPosY(float value) {
        bitField0_ |= 0x00000004;
        posY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float posY = 3;</code>
       */
      public Builder clearPosY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        posY_ = 0F;
        onChanged();
        return this;
      }

      private float scaleX_ ;
      /**
       * <code>required float scaleX = 4;</code>
       */
      public boolean hasScaleX() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required float scaleX = 4;</code>
       */
      public float getScaleX() {
        return scaleX_;
      }
      /**
       * <code>required float scaleX = 4;</code>
       */
      public Builder setScaleX(float value) {
        bitField0_ |= 0x00000008;
        scaleX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float scaleX = 4;</code>
       */
      public Builder clearScaleX() {
        bitField0_ = (bitField0_ & ~0x00000008);
        scaleX_ = 0F;
        onChanged();
        return this;
      }

      private float scaleY_ ;
      /**
       * <code>required float scaleY = 5;</code>
       */
      public boolean hasScaleY() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required float scaleY = 5;</code>
       */
      public float getScaleY() {
        return scaleY_;
      }
      /**
       * <code>required float scaleY = 5;</code>
       */
      public Builder setScaleY(float value) {
        bitField0_ |= 0x00000010;
        scaleY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float scaleY = 5;</code>
       */
      public Builder clearScaleY() {
        bitField0_ = (bitField0_ & ~0x00000010);
        scaleY_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Water)
    }

    static {
      defaultInstance = new Water(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Water)
  }

  public interface VegetationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Vegetation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string uniqueObjectName = 1;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    boolean hasUniqueObjectName();
    /**
     * <code>required string uniqueObjectName = 1;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    java.lang.String getUniqueObjectName();
    /**
     * <code>required string uniqueObjectName = 1;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    com.google.protobuf.ByteString
        getUniqueObjectNameBytes();

    /**
     * <code>required float posX = 2;</code>
     */
    boolean hasPosX();
    /**
     * <code>required float posX = 2;</code>
     */
    float getPosX();

    /**
     * <code>required float posY = 3;</code>
     */
    boolean hasPosY();
    /**
     * <code>required float posY = 3;</code>
     */
    float getPosY();

    /**
     * <code>required float scaleX = 4;</code>
     */
    boolean hasScaleX();
    /**
     * <code>required float scaleX = 4;</code>
     */
    float getScaleX();

    /**
     * <code>required float scaleY = 5;</code>
     */
    boolean hasScaleY();
    /**
     * <code>required float scaleY = 5;</code>
     */
    float getScaleY();
  }
  /**
   * Protobuf type {@code Vegetation}
   */
  public static final class Vegetation extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Vegetation)
      VegetationOrBuilder {
    // Use Vegetation.newBuilder() to construct.
    private Vegetation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Vegetation(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Vegetation defaultInstance;
    public static Vegetation getDefaultInstance() {
      return defaultInstance;
    }

    public Vegetation getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Vegetation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              uniqueObjectName_ = bs;
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              posX_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              posY_ = input.readFloat();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              scaleX_ = input.readFloat();
              break;
            }
            case 45: {
              bitField0_ |= 0x00000010;
              scaleY_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EnvironmentProtos.internal_static_Vegetation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EnvironmentProtos.internal_static_Vegetation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EnvironmentProtos.Vegetation.class, EnvironmentProtos.Vegetation.Builder.class);
    }

    public static com.google.protobuf.Parser<Vegetation> PARSER =
        new com.google.protobuf.AbstractParser<Vegetation>() {
      public Vegetation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Vegetation(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Vegetation> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int UNIQUEOBJECTNAME_FIELD_NUMBER = 1;
    private java.lang.Object uniqueObjectName_;
    /**
     * <code>required string uniqueObjectName = 1;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    public boolean hasUniqueObjectName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string uniqueObjectName = 1;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    public java.lang.String getUniqueObjectName() {
      java.lang.Object ref = uniqueObjectName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uniqueObjectName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string uniqueObjectName = 1;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUniqueObjectNameBytes() {
      java.lang.Object ref = uniqueObjectName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uniqueObjectName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POSX_FIELD_NUMBER = 2;
    private float posX_;
    /**
     * <code>required float posX = 2;</code>
     */
    public boolean hasPosX() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required float posX = 2;</code>
     */
    public float getPosX() {
      return posX_;
    }

    public static final int POSY_FIELD_NUMBER = 3;
    private float posY_;
    /**
     * <code>required float posY = 3;</code>
     */
    public boolean hasPosY() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required float posY = 3;</code>
     */
    public float getPosY() {
      return posY_;
    }

    public static final int SCALEX_FIELD_NUMBER = 4;
    private float scaleX_;
    /**
     * <code>required float scaleX = 4;</code>
     */
    public boolean hasScaleX() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required float scaleX = 4;</code>
     */
    public float getScaleX() {
      return scaleX_;
    }

    public static final int SCALEY_FIELD_NUMBER = 5;
    private float scaleY_;
    /**
     * <code>required float scaleY = 5;</code>
     */
    public boolean hasScaleY() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required float scaleY = 5;</code>
     */
    public float getScaleY() {
      return scaleY_;
    }

    private void initFields() {
      uniqueObjectName_ = "";
      posX_ = 0F;
      posY_ = 0F;
      scaleX_ = 0F;
      scaleY_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUniqueObjectName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPosX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPosY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasScaleX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasScaleY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUniqueObjectNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, posX_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, posY_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, scaleX_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeFloat(5, scaleY_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUniqueObjectNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, posX_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, posY_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, scaleX_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, scaleY_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static EnvironmentProtos.Vegetation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EnvironmentProtos.Vegetation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EnvironmentProtos.Vegetation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EnvironmentProtos.Vegetation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EnvironmentProtos.Vegetation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static EnvironmentProtos.Vegetation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static EnvironmentProtos.Vegetation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static EnvironmentProtos.Vegetation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static EnvironmentProtos.Vegetation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static EnvironmentProtos.Vegetation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(EnvironmentProtos.Vegetation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Vegetation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Vegetation)
        EnvironmentProtos.VegetationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EnvironmentProtos.internal_static_Vegetation_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EnvironmentProtos.internal_static_Vegetation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EnvironmentProtos.Vegetation.class, EnvironmentProtos.Vegetation.Builder.class);
      }

      // Construct using EnvironmentProtos.Vegetation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uniqueObjectName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        posX_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        posY_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        scaleX_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        scaleY_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EnvironmentProtos.internal_static_Vegetation_descriptor;
      }

      public EnvironmentProtos.Vegetation getDefaultInstanceForType() {
        return EnvironmentProtos.Vegetation.getDefaultInstance();
      }

      public EnvironmentProtos.Vegetation build() {
        EnvironmentProtos.Vegetation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public EnvironmentProtos.Vegetation buildPartial() {
        EnvironmentProtos.Vegetation result = new EnvironmentProtos.Vegetation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uniqueObjectName_ = uniqueObjectName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.posX_ = posX_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.posY_ = posY_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.scaleX_ = scaleX_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.scaleY_ = scaleY_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EnvironmentProtos.Vegetation) {
          return mergeFrom((EnvironmentProtos.Vegetation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EnvironmentProtos.Vegetation other) {
        if (other == EnvironmentProtos.Vegetation.getDefaultInstance()) return this;
        if (other.hasUniqueObjectName()) {
          bitField0_ |= 0x00000001;
          uniqueObjectName_ = other.uniqueObjectName_;
          onChanged();
        }
        if (other.hasPosX()) {
          setPosX(other.getPosX());
        }
        if (other.hasPosY()) {
          setPosY(other.getPosY());
        }
        if (other.hasScaleX()) {
          setScaleX(other.getScaleX());
        }
        if (other.hasScaleY()) {
          setScaleY(other.getScaleY());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUniqueObjectName()) {
          
          return false;
        }
        if (!hasPosX()) {
          
          return false;
        }
        if (!hasPosY()) {
          
          return false;
        }
        if (!hasScaleX()) {
          
          return false;
        }
        if (!hasScaleY()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        EnvironmentProtos.Vegetation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (EnvironmentProtos.Vegetation) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object uniqueObjectName_ = "";
      /**
       * <code>required string uniqueObjectName = 1;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public boolean hasUniqueObjectName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string uniqueObjectName = 1;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public java.lang.String getUniqueObjectName() {
        java.lang.Object ref = uniqueObjectName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uniqueObjectName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string uniqueObjectName = 1;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUniqueObjectNameBytes() {
        java.lang.Object ref = uniqueObjectName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uniqueObjectName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string uniqueObjectName = 1;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public Builder setUniqueObjectName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uniqueObjectName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string uniqueObjectName = 1;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public Builder clearUniqueObjectName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uniqueObjectName_ = getDefaultInstance().getUniqueObjectName();
        onChanged();
        return this;
      }
      /**
       * <code>required string uniqueObjectName = 1;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public Builder setUniqueObjectNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uniqueObjectName_ = value;
        onChanged();
        return this;
      }

      private float posX_ ;
      /**
       * <code>required float posX = 2;</code>
       */
      public boolean hasPosX() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float posX = 2;</code>
       */
      public float getPosX() {
        return posX_;
      }
      /**
       * <code>required float posX = 2;</code>
       */
      public Builder setPosX(float value) {
        bitField0_ |= 0x00000002;
        posX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float posX = 2;</code>
       */
      public Builder clearPosX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        posX_ = 0F;
        onChanged();
        return this;
      }

      private float posY_ ;
      /**
       * <code>required float posY = 3;</code>
       */
      public boolean hasPosY() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required float posY = 3;</code>
       */
      public float getPosY() {
        return posY_;
      }
      /**
       * <code>required float posY = 3;</code>
       */
      public Builder setPosY(float value) {
        bitField0_ |= 0x00000004;
        posY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float posY = 3;</code>
       */
      public Builder clearPosY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        posY_ = 0F;
        onChanged();
        return this;
      }

      private float scaleX_ ;
      /**
       * <code>required float scaleX = 4;</code>
       */
      public boolean hasScaleX() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required float scaleX = 4;</code>
       */
      public float getScaleX() {
        return scaleX_;
      }
      /**
       * <code>required float scaleX = 4;</code>
       */
      public Builder setScaleX(float value) {
        bitField0_ |= 0x00000008;
        scaleX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float scaleX = 4;</code>
       */
      public Builder clearScaleX() {
        bitField0_ = (bitField0_ & ~0x00000008);
        scaleX_ = 0F;
        onChanged();
        return this;
      }

      private float scaleY_ ;
      /**
       * <code>required float scaleY = 5;</code>
       */
      public boolean hasScaleY() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required float scaleY = 5;</code>
       */
      public float getScaleY() {
        return scaleY_;
      }
      /**
       * <code>required float scaleY = 5;</code>
       */
      public Builder setScaleY(float value) {
        bitField0_ |= 0x00000010;
        scaleY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float scaleY = 5;</code>
       */
      public Builder clearScaleY() {
        bitField0_ = (bitField0_ & ~0x00000010);
        scaleY_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Vegetation)
    }

    static {
      defaultInstance = new Vegetation(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Vegetation)
  }

  public interface EnvironmentObjectsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EnvironmentObjects)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Water water = 1;</code>
     */
    java.util.List<EnvironmentProtos.Water> 
        getWaterList();
    /**
     * <code>repeated .Water water = 1;</code>
     */
    EnvironmentProtos.Water getWater(int index);
    /**
     * <code>repeated .Water water = 1;</code>
     */
    int getWaterCount();
    /**
     * <code>repeated .Water water = 1;</code>
     */
    java.util.List<? extends EnvironmentProtos.WaterOrBuilder> 
        getWaterOrBuilderList();
    /**
     * <code>repeated .Water water = 1;</code>
     */
    EnvironmentProtos.WaterOrBuilder getWaterOrBuilder(
        int index);

    /**
     * <code>repeated .Vegetation veg = 2;</code>
     */
    java.util.List<EnvironmentProtos.Vegetation> 
        getVegList();
    /**
     * <code>repeated .Vegetation veg = 2;</code>
     */
    EnvironmentProtos.Vegetation getVeg(int index);
    /**
     * <code>repeated .Vegetation veg = 2;</code>
     */
    int getVegCount();
    /**
     * <code>repeated .Vegetation veg = 2;</code>
     */
    java.util.List<? extends EnvironmentProtos.VegetationOrBuilder> 
        getVegOrBuilderList();
    /**
     * <code>repeated .Vegetation veg = 2;</code>
     */
    EnvironmentProtos.VegetationOrBuilder getVegOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code EnvironmentObjects}
   *
   * <pre>
   * Create commands just one of these.
   * </pre>
   */
  public static final class EnvironmentObjects extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:EnvironmentObjects)
      EnvironmentObjectsOrBuilder {
    // Use EnvironmentObjects.newBuilder() to construct.
    private EnvironmentObjects(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EnvironmentObjects(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EnvironmentObjects defaultInstance;
    public static EnvironmentObjects getDefaultInstance() {
      return defaultInstance;
    }

    public EnvironmentObjects getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EnvironmentObjects(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                water_ = new java.util.ArrayList<EnvironmentProtos.Water>();
                mutable_bitField0_ |= 0x00000001;
              }
              water_.add(input.readMessage(EnvironmentProtos.Water.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                veg_ = new java.util.ArrayList<EnvironmentProtos.Vegetation>();
                mutable_bitField0_ |= 0x00000002;
              }
              veg_.add(input.readMessage(EnvironmentProtos.Vegetation.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          water_ = java.util.Collections.unmodifiableList(water_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          veg_ = java.util.Collections.unmodifiableList(veg_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EnvironmentProtos.internal_static_EnvironmentObjects_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EnvironmentProtos.internal_static_EnvironmentObjects_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EnvironmentProtos.EnvironmentObjects.class, EnvironmentProtos.EnvironmentObjects.Builder.class);
    }

    public static com.google.protobuf.Parser<EnvironmentObjects> PARSER =
        new com.google.protobuf.AbstractParser<EnvironmentObjects>() {
      public EnvironmentObjects parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EnvironmentObjects(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EnvironmentObjects> getParserForType() {
      return PARSER;
    }

    public static final int WATER_FIELD_NUMBER = 1;
    private java.util.List<EnvironmentProtos.Water> water_;
    /**
     * <code>repeated .Water water = 1;</code>
     */
    public java.util.List<EnvironmentProtos.Water> getWaterList() {
      return water_;
    }
    /**
     * <code>repeated .Water water = 1;</code>
     */
    public java.util.List<? extends EnvironmentProtos.WaterOrBuilder> 
        getWaterOrBuilderList() {
      return water_;
    }
    /**
     * <code>repeated .Water water = 1;</code>
     */
    public int getWaterCount() {
      return water_.size();
    }
    /**
     * <code>repeated .Water water = 1;</code>
     */
    public EnvironmentProtos.Water getWater(int index) {
      return water_.get(index);
    }
    /**
     * <code>repeated .Water water = 1;</code>
     */
    public EnvironmentProtos.WaterOrBuilder getWaterOrBuilder(
        int index) {
      return water_.get(index);
    }

    public static final int VEG_FIELD_NUMBER = 2;
    private java.util.List<EnvironmentProtos.Vegetation> veg_;
    /**
     * <code>repeated .Vegetation veg = 2;</code>
     */
    public java.util.List<EnvironmentProtos.Vegetation> getVegList() {
      return veg_;
    }
    /**
     * <code>repeated .Vegetation veg = 2;</code>
     */
    public java.util.List<? extends EnvironmentProtos.VegetationOrBuilder> 
        getVegOrBuilderList() {
      return veg_;
    }
    /**
     * <code>repeated .Vegetation veg = 2;</code>
     */
    public int getVegCount() {
      return veg_.size();
    }
    /**
     * <code>repeated .Vegetation veg = 2;</code>
     */
    public EnvironmentProtos.Vegetation getVeg(int index) {
      return veg_.get(index);
    }
    /**
     * <code>repeated .Vegetation veg = 2;</code>
     */
    public EnvironmentProtos.VegetationOrBuilder getVegOrBuilder(
        int index) {
      return veg_.get(index);
    }

    private void initFields() {
      water_ = java.util.Collections.emptyList();
      veg_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getWaterCount(); i++) {
        if (!getWater(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getVegCount(); i++) {
        if (!getVeg(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < water_.size(); i++) {
        output.writeMessage(1, water_.get(i));
      }
      for (int i = 0; i < veg_.size(); i++) {
        output.writeMessage(2, veg_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < water_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, water_.get(i));
      }
      for (int i = 0; i < veg_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, veg_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static EnvironmentProtos.EnvironmentObjects parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EnvironmentProtos.EnvironmentObjects parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EnvironmentProtos.EnvironmentObjects parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EnvironmentProtos.EnvironmentObjects parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EnvironmentProtos.EnvironmentObjects parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static EnvironmentProtos.EnvironmentObjects parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static EnvironmentProtos.EnvironmentObjects parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static EnvironmentProtos.EnvironmentObjects parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static EnvironmentProtos.EnvironmentObjects parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static EnvironmentProtos.EnvironmentObjects parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(EnvironmentProtos.EnvironmentObjects prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code EnvironmentObjects}
     *
     * <pre>
     * Create commands just one of these.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EnvironmentObjects)
        EnvironmentProtos.EnvironmentObjectsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EnvironmentProtos.internal_static_EnvironmentObjects_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EnvironmentProtos.internal_static_EnvironmentObjects_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EnvironmentProtos.EnvironmentObjects.class, EnvironmentProtos.EnvironmentObjects.Builder.class);
      }

      // Construct using EnvironmentProtos.EnvironmentObjects.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getWaterFieldBuilder();
          getVegFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (waterBuilder_ == null) {
          water_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          waterBuilder_.clear();
        }
        if (vegBuilder_ == null) {
          veg_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          vegBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EnvironmentProtos.internal_static_EnvironmentObjects_descriptor;
      }

      public EnvironmentProtos.EnvironmentObjects getDefaultInstanceForType() {
        return EnvironmentProtos.EnvironmentObjects.getDefaultInstance();
      }

      public EnvironmentProtos.EnvironmentObjects build() {
        EnvironmentProtos.EnvironmentObjects result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public EnvironmentProtos.EnvironmentObjects buildPartial() {
        EnvironmentProtos.EnvironmentObjects result = new EnvironmentProtos.EnvironmentObjects(this);
        int from_bitField0_ = bitField0_;
        if (waterBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            water_ = java.util.Collections.unmodifiableList(water_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.water_ = water_;
        } else {
          result.water_ = waterBuilder_.build();
        }
        if (vegBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            veg_ = java.util.Collections.unmodifiableList(veg_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.veg_ = veg_;
        } else {
          result.veg_ = vegBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EnvironmentProtos.EnvironmentObjects) {
          return mergeFrom((EnvironmentProtos.EnvironmentObjects)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EnvironmentProtos.EnvironmentObjects other) {
        if (other == EnvironmentProtos.EnvironmentObjects.getDefaultInstance()) return this;
        if (waterBuilder_ == null) {
          if (!other.water_.isEmpty()) {
            if (water_.isEmpty()) {
              water_ = other.water_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureWaterIsMutable();
              water_.addAll(other.water_);
            }
            onChanged();
          }
        } else {
          if (!other.water_.isEmpty()) {
            if (waterBuilder_.isEmpty()) {
              waterBuilder_.dispose();
              waterBuilder_ = null;
              water_ = other.water_;
              bitField0_ = (bitField0_ & ~0x00000001);
              waterBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getWaterFieldBuilder() : null;
            } else {
              waterBuilder_.addAllMessages(other.water_);
            }
          }
        }
        if (vegBuilder_ == null) {
          if (!other.veg_.isEmpty()) {
            if (veg_.isEmpty()) {
              veg_ = other.veg_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureVegIsMutable();
              veg_.addAll(other.veg_);
            }
            onChanged();
          }
        } else {
          if (!other.veg_.isEmpty()) {
            if (vegBuilder_.isEmpty()) {
              vegBuilder_.dispose();
              vegBuilder_ = null;
              veg_ = other.veg_;
              bitField0_ = (bitField0_ & ~0x00000002);
              vegBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getVegFieldBuilder() : null;
            } else {
              vegBuilder_.addAllMessages(other.veg_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getWaterCount(); i++) {
          if (!getWater(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getVegCount(); i++) {
          if (!getVeg(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        EnvironmentProtos.EnvironmentObjects parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (EnvironmentProtos.EnvironmentObjects) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<EnvironmentProtos.Water> water_ =
        java.util.Collections.emptyList();
      private void ensureWaterIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          water_ = new java.util.ArrayList<EnvironmentProtos.Water>(water_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          EnvironmentProtos.Water, EnvironmentProtos.Water.Builder, EnvironmentProtos.WaterOrBuilder> waterBuilder_;

      /**
       * <code>repeated .Water water = 1;</code>
       */
      public java.util.List<EnvironmentProtos.Water> getWaterList() {
        if (waterBuilder_ == null) {
          return java.util.Collections.unmodifiableList(water_);
        } else {
          return waterBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Water water = 1;</code>
       */
      public int getWaterCount() {
        if (waterBuilder_ == null) {
          return water_.size();
        } else {
          return waterBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Water water = 1;</code>
       */
      public EnvironmentProtos.Water getWater(int index) {
        if (waterBuilder_ == null) {
          return water_.get(index);
        } else {
          return waterBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Water water = 1;</code>
       */
      public Builder setWater(
          int index, EnvironmentProtos.Water value) {
        if (waterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWaterIsMutable();
          water_.set(index, value);
          onChanged();
        } else {
          waterBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Water water = 1;</code>
       */
      public Builder setWater(
          int index, EnvironmentProtos.Water.Builder builderForValue) {
        if (waterBuilder_ == null) {
          ensureWaterIsMutable();
          water_.set(index, builderForValue.build());
          onChanged();
        } else {
          waterBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Water water = 1;</code>
       */
      public Builder addWater(EnvironmentProtos.Water value) {
        if (waterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWaterIsMutable();
          water_.add(value);
          onChanged();
        } else {
          waterBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Water water = 1;</code>
       */
      public Builder addWater(
          int index, EnvironmentProtos.Water value) {
        if (waterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWaterIsMutable();
          water_.add(index, value);
          onChanged();
        } else {
          waterBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Water water = 1;</code>
       */
      public Builder addWater(
          EnvironmentProtos.Water.Builder builderForValue) {
        if (waterBuilder_ == null) {
          ensureWaterIsMutable();
          water_.add(builderForValue.build());
          onChanged();
        } else {
          waterBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Water water = 1;</code>
       */
      public Builder addWater(
          int index, EnvironmentProtos.Water.Builder builderForValue) {
        if (waterBuilder_ == null) {
          ensureWaterIsMutable();
          water_.add(index, builderForValue.build());
          onChanged();
        } else {
          waterBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Water water = 1;</code>
       */
      public Builder addAllWater(
          java.lang.Iterable<? extends EnvironmentProtos.Water> values) {
        if (waterBuilder_ == null) {
          ensureWaterIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, water_);
          onChanged();
        } else {
          waterBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Water water = 1;</code>
       */
      public Builder clearWater() {
        if (waterBuilder_ == null) {
          water_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          waterBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Water water = 1;</code>
       */
      public Builder removeWater(int index) {
        if (waterBuilder_ == null) {
          ensureWaterIsMutable();
          water_.remove(index);
          onChanged();
        } else {
          waterBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Water water = 1;</code>
       */
      public EnvironmentProtos.Water.Builder getWaterBuilder(
          int index) {
        return getWaterFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Water water = 1;</code>
       */
      public EnvironmentProtos.WaterOrBuilder getWaterOrBuilder(
          int index) {
        if (waterBuilder_ == null) {
          return water_.get(index);  } else {
          return waterBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Water water = 1;</code>
       */
      public java.util.List<? extends EnvironmentProtos.WaterOrBuilder> 
           getWaterOrBuilderList() {
        if (waterBuilder_ != null) {
          return waterBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(water_);
        }
      }
      /**
       * <code>repeated .Water water = 1;</code>
       */
      public EnvironmentProtos.Water.Builder addWaterBuilder() {
        return getWaterFieldBuilder().addBuilder(
            EnvironmentProtos.Water.getDefaultInstance());
      }
      /**
       * <code>repeated .Water water = 1;</code>
       */
      public EnvironmentProtos.Water.Builder addWaterBuilder(
          int index) {
        return getWaterFieldBuilder().addBuilder(
            index, EnvironmentProtos.Water.getDefaultInstance());
      }
      /**
       * <code>repeated .Water water = 1;</code>
       */
      public java.util.List<EnvironmentProtos.Water.Builder> 
           getWaterBuilderList() {
        return getWaterFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          EnvironmentProtos.Water, EnvironmentProtos.Water.Builder, EnvironmentProtos.WaterOrBuilder> 
          getWaterFieldBuilder() {
        if (waterBuilder_ == null) {
          waterBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              EnvironmentProtos.Water, EnvironmentProtos.Water.Builder, EnvironmentProtos.WaterOrBuilder>(
                  water_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          water_ = null;
        }
        return waterBuilder_;
      }

      private java.util.List<EnvironmentProtos.Vegetation> veg_ =
        java.util.Collections.emptyList();
      private void ensureVegIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          veg_ = new java.util.ArrayList<EnvironmentProtos.Vegetation>(veg_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          EnvironmentProtos.Vegetation, EnvironmentProtos.Vegetation.Builder, EnvironmentProtos.VegetationOrBuilder> vegBuilder_;

      /**
       * <code>repeated .Vegetation veg = 2;</code>
       */
      public java.util.List<EnvironmentProtos.Vegetation> getVegList() {
        if (vegBuilder_ == null) {
          return java.util.Collections.unmodifiableList(veg_);
        } else {
          return vegBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Vegetation veg = 2;</code>
       */
      public int getVegCount() {
        if (vegBuilder_ == null) {
          return veg_.size();
        } else {
          return vegBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Vegetation veg = 2;</code>
       */
      public EnvironmentProtos.Vegetation getVeg(int index) {
        if (vegBuilder_ == null) {
          return veg_.get(index);
        } else {
          return vegBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Vegetation veg = 2;</code>
       */
      public Builder setVeg(
          int index, EnvironmentProtos.Vegetation value) {
        if (vegBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVegIsMutable();
          veg_.set(index, value);
          onChanged();
        } else {
          vegBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Vegetation veg = 2;</code>
       */
      public Builder setVeg(
          int index, EnvironmentProtos.Vegetation.Builder builderForValue) {
        if (vegBuilder_ == null) {
          ensureVegIsMutable();
          veg_.set(index, builderForValue.build());
          onChanged();
        } else {
          vegBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Vegetation veg = 2;</code>
       */
      public Builder addVeg(EnvironmentProtos.Vegetation value) {
        if (vegBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVegIsMutable();
          veg_.add(value);
          onChanged();
        } else {
          vegBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Vegetation veg = 2;</code>
       */
      public Builder addVeg(
          int index, EnvironmentProtos.Vegetation value) {
        if (vegBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVegIsMutable();
          veg_.add(index, value);
          onChanged();
        } else {
          vegBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Vegetation veg = 2;</code>
       */
      public Builder addVeg(
          EnvironmentProtos.Vegetation.Builder builderForValue) {
        if (vegBuilder_ == null) {
          ensureVegIsMutable();
          veg_.add(builderForValue.build());
          onChanged();
        } else {
          vegBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Vegetation veg = 2;</code>
       */
      public Builder addVeg(
          int index, EnvironmentProtos.Vegetation.Builder builderForValue) {
        if (vegBuilder_ == null) {
          ensureVegIsMutable();
          veg_.add(index, builderForValue.build());
          onChanged();
        } else {
          vegBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Vegetation veg = 2;</code>
       */
      public Builder addAllVeg(
          java.lang.Iterable<? extends EnvironmentProtos.Vegetation> values) {
        if (vegBuilder_ == null) {
          ensureVegIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, veg_);
          onChanged();
        } else {
          vegBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Vegetation veg = 2;</code>
       */
      public Builder clearVeg() {
        if (vegBuilder_ == null) {
          veg_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          vegBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Vegetation veg = 2;</code>
       */
      public Builder removeVeg(int index) {
        if (vegBuilder_ == null) {
          ensureVegIsMutable();
          veg_.remove(index);
          onChanged();
        } else {
          vegBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Vegetation veg = 2;</code>
       */
      public EnvironmentProtos.Vegetation.Builder getVegBuilder(
          int index) {
        return getVegFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Vegetation veg = 2;</code>
       */
      public EnvironmentProtos.VegetationOrBuilder getVegOrBuilder(
          int index) {
        if (vegBuilder_ == null) {
          return veg_.get(index);  } else {
          return vegBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Vegetation veg = 2;</code>
       */
      public java.util.List<? extends EnvironmentProtos.VegetationOrBuilder> 
           getVegOrBuilderList() {
        if (vegBuilder_ != null) {
          return vegBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(veg_);
        }
      }
      /**
       * <code>repeated .Vegetation veg = 2;</code>
       */
      public EnvironmentProtos.Vegetation.Builder addVegBuilder() {
        return getVegFieldBuilder().addBuilder(
            EnvironmentProtos.Vegetation.getDefaultInstance());
      }
      /**
       * <code>repeated .Vegetation veg = 2;</code>
       */
      public EnvironmentProtos.Vegetation.Builder addVegBuilder(
          int index) {
        return getVegFieldBuilder().addBuilder(
            index, EnvironmentProtos.Vegetation.getDefaultInstance());
      }
      /**
       * <code>repeated .Vegetation veg = 2;</code>
       */
      public java.util.List<EnvironmentProtos.Vegetation.Builder> 
           getVegBuilderList() {
        return getVegFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          EnvironmentProtos.Vegetation, EnvironmentProtos.Vegetation.Builder, EnvironmentProtos.VegetationOrBuilder> 
          getVegFieldBuilder() {
        if (vegBuilder_ == null) {
          vegBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              EnvironmentProtos.Vegetation, EnvironmentProtos.Vegetation.Builder, EnvironmentProtos.VegetationOrBuilder>(
                  veg_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          veg_ = null;
        }
        return vegBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:EnvironmentObjects)
    }

    static {
      defaultInstance = new EnvironmentObjects(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:EnvironmentObjects)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Water_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Water_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Vegetation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Vegetation_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnvironmentObjects_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_EnvironmentObjects_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021Environment.proto\"]\n\005Water\022\030\n\020uniqueOb" +
      "jectName\030\001 \002(\t\022\014\n\004posX\030\002 \002(\002\022\014\n\004posY\030\003 \002" +
      "(\002\022\016\n\006scaleX\030\004 \002(\002\022\016\n\006scaleY\030\005 \002(\002\"b\n\nVe" +
      "getation\022\030\n\020uniqueObjectName\030\001 \002(\t\022\014\n\004po" +
      "sX\030\002 \002(\002\022\014\n\004posY\030\003 \002(\002\022\016\n\006scaleX\030\004 \002(\002\022\016" +
      "\n\006scaleY\030\005 \002(\002\"E\n\022EnvironmentObjects\022\025\n\005" +
      "water\030\001 \003(\0132\006.Water\022\030\n\003veg\030\002 \003(\0132\013.Veget" +
      "ationB\023B\021EnvironmentProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Water_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Water_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Water_descriptor,
        new java.lang.String[] { "UniqueObjectName", "PosX", "PosY", "ScaleX", "ScaleY", });
    internal_static_Vegetation_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Vegetation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Vegetation_descriptor,
        new java.lang.String[] { "UniqueObjectName", "PosX", "PosY", "ScaleX", "ScaleY", });
    internal_static_EnvironmentObjects_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_EnvironmentObjects_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_EnvironmentObjects_descriptor,
        new java.lang.String[] { "Water", "Veg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
