# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NewTargets.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='NewTargets.proto',
  package='',
  serialized_pb=_b('\n\x10NewTargets.proto\"D\n\tNewTarget\x12\x18\n\x10uniqueObjectName\x18\x01 \x02(\t\x12\r\n\x05state\x18\x02 \x02(\x05\x12\x0e\n\x06target\x18\x03 \x02(\t\"+\n\nNewTargets\x12\x1d\n\tnewTarget\x18\x01 \x03(\x0b\x32\n.NewTargetB\x12\x42\x10NewTargetsProtos')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_NEWTARGET = _descriptor.Descriptor(
  name='NewTarget',
  full_name='NewTarget',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uniqueObjectName', full_name='NewTarget.uniqueObjectName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='NewTarget.state', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target', full_name='NewTarget.target', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=88,
)


_NEWTARGETS = _descriptor.Descriptor(
  name='NewTargets',
  full_name='NewTargets',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='newTarget', full_name='NewTargets.newTarget', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=133,
)

_NEWTARGETS.fields_by_name['newTarget'].message_type = _NEWTARGET
DESCRIPTOR.message_types_by_name['NewTarget'] = _NEWTARGET
DESCRIPTOR.message_types_by_name['NewTargets'] = _NEWTARGETS

NewTarget = _reflection.GeneratedProtocolMessageType('NewTarget', (_message.Message,), dict(
  DESCRIPTOR = _NEWTARGET,
  __module__ = 'NewTargets_pb2'
  # @@protoc_insertion_point(class_scope:NewTarget)
  ))
_sym_db.RegisterMessage(NewTarget)

NewTargets = _reflection.GeneratedProtocolMessageType('NewTargets', (_message.Message,), dict(
  DESCRIPTOR = _NEWTARGETS,
  __module__ = 'NewTargets_pb2'
  # @@protoc_insertion_point(class_scope:NewTargets)
  ))
_sym_db.RegisterMessage(NewTargets)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\020NewTargetsProtos'))
# @@protoc_insertion_point(module_scope)
