package ProtoBufProtos;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NewTargets.proto

public final class NewTargetsProtos {
  private NewTargetsProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NewTargetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NewTarget)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string uniqueObjectName = 1;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    boolean hasUniqueObjectName();
    /**
     * <code>required string uniqueObjectName = 1;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    java.lang.String getUniqueObjectName();
    /**
     * <code>required string uniqueObjectName = 1;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    com.google.protobuf.ByteString
        getUniqueObjectNameBytes();

    /**
     * <code>required int32 state = 2;</code>
     */
    boolean hasState();
    /**
     * <code>required int32 state = 2;</code>
     */
    int getState();

    /**
     * <code>required string target = 3;</code>
     */
    boolean hasTarget();
    /**
     * <code>required string target = 3;</code>
     */
    java.lang.String getTarget();
    /**
     * <code>required string target = 3;</code>
     */
    com.google.protobuf.ByteString
        getTargetBytes();
  }
  /**
   * Protobuf type {@code NewTarget}
   */
  public static final class NewTarget extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:NewTarget)
      NewTargetOrBuilder {
    // Use NewTarget.newBuilder() to construct.
    private NewTarget(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NewTarget(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NewTarget defaultInstance;
    public static NewTarget getDefaultInstance() {
      return defaultInstance;
    }

    public NewTarget getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NewTarget(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              uniqueObjectName_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              state_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              target_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NewTargetsProtos.internal_static_NewTarget_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NewTargetsProtos.internal_static_NewTarget_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NewTargetsProtos.NewTarget.class, NewTargetsProtos.NewTarget.Builder.class);
    }

    public static com.google.protobuf.Parser<NewTarget> PARSER =
        new com.google.protobuf.AbstractParser<NewTarget>() {
      public NewTarget parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NewTarget(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NewTarget> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int UNIQUEOBJECTNAME_FIELD_NUMBER = 1;
    private java.lang.Object uniqueObjectName_;
    /**
     * <code>required string uniqueObjectName = 1;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    public boolean hasUniqueObjectName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string uniqueObjectName = 1;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    public java.lang.String getUniqueObjectName() {
      java.lang.Object ref = uniqueObjectName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uniqueObjectName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string uniqueObjectName = 1;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUniqueObjectNameBytes() {
      java.lang.Object ref = uniqueObjectName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uniqueObjectName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATE_FIELD_NUMBER = 2;
    private int state_;
    /**
     * <code>required int32 state = 2;</code>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 state = 2;</code>
     */
    public int getState() {
      return state_;
    }

    public static final int TARGET_FIELD_NUMBER = 3;
    private java.lang.Object target_;
    /**
     * <code>required string target = 3;</code>
     */
    public boolean hasTarget() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string target = 3;</code>
     */
    public java.lang.String getTarget() {
      java.lang.Object ref = target_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          target_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string target = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTargetBytes() {
      java.lang.Object ref = target_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        target_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      uniqueObjectName_ = "";
      state_ = 0;
      target_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUniqueObjectName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTarget()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUniqueObjectNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, state_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTargetBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUniqueObjectNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, state_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTargetBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static NewTargetsProtos.NewTarget parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NewTargetsProtos.NewTarget parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NewTargetsProtos.NewTarget parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NewTargetsProtos.NewTarget parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NewTargetsProtos.NewTarget parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static NewTargetsProtos.NewTarget parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static NewTargetsProtos.NewTarget parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static NewTargetsProtos.NewTarget parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static NewTargetsProtos.NewTarget parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static NewTargetsProtos.NewTarget parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(NewTargetsProtos.NewTarget prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NewTarget}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NewTarget)
        NewTargetsProtos.NewTargetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NewTargetsProtos.internal_static_NewTarget_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NewTargetsProtos.internal_static_NewTarget_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NewTargetsProtos.NewTarget.class, NewTargetsProtos.NewTarget.Builder.class);
      }

      // Construct using NewTargetsProtos.NewTarget.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uniqueObjectName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        state_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        target_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NewTargetsProtos.internal_static_NewTarget_descriptor;
      }

      public NewTargetsProtos.NewTarget getDefaultInstanceForType() {
        return NewTargetsProtos.NewTarget.getDefaultInstance();
      }

      public NewTargetsProtos.NewTarget build() {
        NewTargetsProtos.NewTarget result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public NewTargetsProtos.NewTarget buildPartial() {
        NewTargetsProtos.NewTarget result = new NewTargetsProtos.NewTarget(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uniqueObjectName_ = uniqueObjectName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.target_ = target_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NewTargetsProtos.NewTarget) {
          return mergeFrom((NewTargetsProtos.NewTarget)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NewTargetsProtos.NewTarget other) {
        if (other == NewTargetsProtos.NewTarget.getDefaultInstance()) return this;
        if (other.hasUniqueObjectName()) {
          bitField0_ |= 0x00000001;
          uniqueObjectName_ = other.uniqueObjectName_;
          onChanged();
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasTarget()) {
          bitField0_ |= 0x00000004;
          target_ = other.target_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUniqueObjectName()) {
          
          return false;
        }
        if (!hasState()) {
          
          return false;
        }
        if (!hasTarget()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        NewTargetsProtos.NewTarget parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (NewTargetsProtos.NewTarget) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object uniqueObjectName_ = "";
      /**
       * <code>required string uniqueObjectName = 1;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public boolean hasUniqueObjectName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string uniqueObjectName = 1;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public java.lang.String getUniqueObjectName() {
        java.lang.Object ref = uniqueObjectName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uniqueObjectName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string uniqueObjectName = 1;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUniqueObjectNameBytes() {
        java.lang.Object ref = uniqueObjectName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uniqueObjectName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string uniqueObjectName = 1;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public Builder setUniqueObjectName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uniqueObjectName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string uniqueObjectName = 1;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public Builder clearUniqueObjectName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uniqueObjectName_ = getDefaultInstance().getUniqueObjectName();
        onChanged();
        return this;
      }
      /**
       * <code>required string uniqueObjectName = 1;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public Builder setUniqueObjectNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uniqueObjectName_ = value;
        onChanged();
        return this;
      }

      private int state_ ;
      /**
       * <code>required int32 state = 2;</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 state = 2;</code>
       */
      public int getState() {
        return state_;
      }
      /**
       * <code>required int32 state = 2;</code>
       */
      public Builder setState(int value) {
        bitField0_ |= 0x00000002;
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 state = 2;</code>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000002);
        state_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object target_ = "";
      /**
       * <code>required string target = 3;</code>
       */
      public boolean hasTarget() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string target = 3;</code>
       */
      public java.lang.String getTarget() {
        java.lang.Object ref = target_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            target_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string target = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTargetBytes() {
        java.lang.Object ref = target_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          target_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string target = 3;</code>
       */
      public Builder setTarget(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        target_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string target = 3;</code>
       */
      public Builder clearTarget() {
        bitField0_ = (bitField0_ & ~0x00000004);
        target_ = getDefaultInstance().getTarget();
        onChanged();
        return this;
      }
      /**
       * <code>required string target = 3;</code>
       */
      public Builder setTargetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        target_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NewTarget)
    }

    static {
      defaultInstance = new NewTarget(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NewTarget)
  }

  public interface NewTargetsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NewTargets)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .NewTarget newTarget = 1;</code>
     */
    java.util.List<NewTargetsProtos.NewTarget> 
        getNewTargetList();
    /**
     * <code>repeated .NewTarget newTarget = 1;</code>
     */
    NewTargetsProtos.NewTarget getNewTarget(int index);
    /**
     * <code>repeated .NewTarget newTarget = 1;</code>
     */
    int getNewTargetCount();
    /**
     * <code>repeated .NewTarget newTarget = 1;</code>
     */
    java.util.List<? extends NewTargetsProtos.NewTargetOrBuilder> 
        getNewTargetOrBuilderList();
    /**
     * <code>repeated .NewTarget newTarget = 1;</code>
     */
    NewTargetsProtos.NewTargetOrBuilder getNewTargetOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code NewTargets}
   *
   * <pre>
   * Create commands just one of these.
   * </pre>
   */
  public static final class NewTargets extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:NewTargets)
      NewTargetsOrBuilder {
    // Use NewTargets.newBuilder() to construct.
    private NewTargets(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NewTargets(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NewTargets defaultInstance;
    public static NewTargets getDefaultInstance() {
      return defaultInstance;
    }

    public NewTargets getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NewTargets(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                newTarget_ = new java.util.ArrayList<NewTargetsProtos.NewTarget>();
                mutable_bitField0_ |= 0x00000001;
              }
              newTarget_.add(input.readMessage(NewTargetsProtos.NewTarget.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          newTarget_ = java.util.Collections.unmodifiableList(newTarget_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NewTargetsProtos.internal_static_NewTargets_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NewTargetsProtos.internal_static_NewTargets_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NewTargetsProtos.NewTargets.class, NewTargetsProtos.NewTargets.Builder.class);
    }

    public static com.google.protobuf.Parser<NewTargets> PARSER =
        new com.google.protobuf.AbstractParser<NewTargets>() {
      public NewTargets parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NewTargets(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NewTargets> getParserForType() {
      return PARSER;
    }

    public static final int NEWTARGET_FIELD_NUMBER = 1;
    private java.util.List<NewTargetsProtos.NewTarget> newTarget_;
    /**
     * <code>repeated .NewTarget newTarget = 1;</code>
     */
    public java.util.List<NewTargetsProtos.NewTarget> getNewTargetList() {
      return newTarget_;
    }
    /**
     * <code>repeated .NewTarget newTarget = 1;</code>
     */
    public java.util.List<? extends NewTargetsProtos.NewTargetOrBuilder> 
        getNewTargetOrBuilderList() {
      return newTarget_;
    }
    /**
     * <code>repeated .NewTarget newTarget = 1;</code>
     */
    public int getNewTargetCount() {
      return newTarget_.size();
    }
    /**
     * <code>repeated .NewTarget newTarget = 1;</code>
     */
    public NewTargetsProtos.NewTarget getNewTarget(int index) {
      return newTarget_.get(index);
    }
    /**
     * <code>repeated .NewTarget newTarget = 1;</code>
     */
    public NewTargetsProtos.NewTargetOrBuilder getNewTargetOrBuilder(
        int index) {
      return newTarget_.get(index);
    }

    private void initFields() {
      newTarget_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getNewTargetCount(); i++) {
        if (!getNewTarget(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < newTarget_.size(); i++) {
        output.writeMessage(1, newTarget_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < newTarget_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, newTarget_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static NewTargetsProtos.NewTargets parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NewTargetsProtos.NewTargets parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NewTargetsProtos.NewTargets parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NewTargetsProtos.NewTargets parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NewTargetsProtos.NewTargets parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static NewTargetsProtos.NewTargets parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static NewTargetsProtos.NewTargets parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static NewTargetsProtos.NewTargets parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static NewTargetsProtos.NewTargets parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static NewTargetsProtos.NewTargets parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(NewTargetsProtos.NewTargets prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NewTargets}
     *
     * <pre>
     * Create commands just one of these.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NewTargets)
        NewTargetsProtos.NewTargetsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NewTargetsProtos.internal_static_NewTargets_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NewTargetsProtos.internal_static_NewTargets_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NewTargetsProtos.NewTargets.class, NewTargetsProtos.NewTargets.Builder.class);
      }

      // Construct using NewTargetsProtos.NewTargets.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getNewTargetFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (newTargetBuilder_ == null) {
          newTarget_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          newTargetBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NewTargetsProtos.internal_static_NewTargets_descriptor;
      }

      public NewTargetsProtos.NewTargets getDefaultInstanceForType() {
        return NewTargetsProtos.NewTargets.getDefaultInstance();
      }

      public NewTargetsProtos.NewTargets build() {
        NewTargetsProtos.NewTargets result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public NewTargetsProtos.NewTargets buildPartial() {
        NewTargetsProtos.NewTargets result = new NewTargetsProtos.NewTargets(this);
        int from_bitField0_ = bitField0_;
        if (newTargetBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            newTarget_ = java.util.Collections.unmodifiableList(newTarget_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.newTarget_ = newTarget_;
        } else {
          result.newTarget_ = newTargetBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NewTargetsProtos.NewTargets) {
          return mergeFrom((NewTargetsProtos.NewTargets)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NewTargetsProtos.NewTargets other) {
        if (other == NewTargetsProtos.NewTargets.getDefaultInstance()) return this;
        if (newTargetBuilder_ == null) {
          if (!other.newTarget_.isEmpty()) {
            if (newTarget_.isEmpty()) {
              newTarget_ = other.newTarget_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNewTargetIsMutable();
              newTarget_.addAll(other.newTarget_);
            }
            onChanged();
          }
        } else {
          if (!other.newTarget_.isEmpty()) {
            if (newTargetBuilder_.isEmpty()) {
              newTargetBuilder_.dispose();
              newTargetBuilder_ = null;
              newTarget_ = other.newTarget_;
              bitField0_ = (bitField0_ & ~0x00000001);
              newTargetBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getNewTargetFieldBuilder() : null;
            } else {
              newTargetBuilder_.addAllMessages(other.newTarget_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getNewTargetCount(); i++) {
          if (!getNewTarget(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        NewTargetsProtos.NewTargets parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (NewTargetsProtos.NewTargets) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<NewTargetsProtos.NewTarget> newTarget_ =
        java.util.Collections.emptyList();
      private void ensureNewTargetIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          newTarget_ = new java.util.ArrayList<NewTargetsProtos.NewTarget>(newTarget_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          NewTargetsProtos.NewTarget, NewTargetsProtos.NewTarget.Builder, NewTargetsProtos.NewTargetOrBuilder> newTargetBuilder_;

      /**
       * <code>repeated .NewTarget newTarget = 1;</code>
       */
      public java.util.List<NewTargetsProtos.NewTarget> getNewTargetList() {
        if (newTargetBuilder_ == null) {
          return java.util.Collections.unmodifiableList(newTarget_);
        } else {
          return newTargetBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .NewTarget newTarget = 1;</code>
       */
      public int getNewTargetCount() {
        if (newTargetBuilder_ == null) {
          return newTarget_.size();
        } else {
          return newTargetBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .NewTarget newTarget = 1;</code>
       */
      public NewTargetsProtos.NewTarget getNewTarget(int index) {
        if (newTargetBuilder_ == null) {
          return newTarget_.get(index);
        } else {
          return newTargetBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .NewTarget newTarget = 1;</code>
       */
      public Builder setNewTarget(
          int index, NewTargetsProtos.NewTarget value) {
        if (newTargetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNewTargetIsMutable();
          newTarget_.set(index, value);
          onChanged();
        } else {
          newTargetBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NewTarget newTarget = 1;</code>
       */
      public Builder setNewTarget(
          int index, NewTargetsProtos.NewTarget.Builder builderForValue) {
        if (newTargetBuilder_ == null) {
          ensureNewTargetIsMutable();
          newTarget_.set(index, builderForValue.build());
          onChanged();
        } else {
          newTargetBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NewTarget newTarget = 1;</code>
       */
      public Builder addNewTarget(NewTargetsProtos.NewTarget value) {
        if (newTargetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNewTargetIsMutable();
          newTarget_.add(value);
          onChanged();
        } else {
          newTargetBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .NewTarget newTarget = 1;</code>
       */
      public Builder addNewTarget(
          int index, NewTargetsProtos.NewTarget value) {
        if (newTargetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNewTargetIsMutable();
          newTarget_.add(index, value);
          onChanged();
        } else {
          newTargetBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NewTarget newTarget = 1;</code>
       */
      public Builder addNewTarget(
          NewTargetsProtos.NewTarget.Builder builderForValue) {
        if (newTargetBuilder_ == null) {
          ensureNewTargetIsMutable();
          newTarget_.add(builderForValue.build());
          onChanged();
        } else {
          newTargetBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NewTarget newTarget = 1;</code>
       */
      public Builder addNewTarget(
          int index, NewTargetsProtos.NewTarget.Builder builderForValue) {
        if (newTargetBuilder_ == null) {
          ensureNewTargetIsMutable();
          newTarget_.add(index, builderForValue.build());
          onChanged();
        } else {
          newTargetBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NewTarget newTarget = 1;</code>
       */
      public Builder addAllNewTarget(
          java.lang.Iterable<? extends NewTargetsProtos.NewTarget> values) {
        if (newTargetBuilder_ == null) {
          ensureNewTargetIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, newTarget_);
          onChanged();
        } else {
          newTargetBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .NewTarget newTarget = 1;</code>
       */
      public Builder clearNewTarget() {
        if (newTargetBuilder_ == null) {
          newTarget_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          newTargetBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .NewTarget newTarget = 1;</code>
       */
      public Builder removeNewTarget(int index) {
        if (newTargetBuilder_ == null) {
          ensureNewTargetIsMutable();
          newTarget_.remove(index);
          onChanged();
        } else {
          newTargetBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .NewTarget newTarget = 1;</code>
       */
      public NewTargetsProtos.NewTarget.Builder getNewTargetBuilder(
          int index) {
        return getNewTargetFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .NewTarget newTarget = 1;</code>
       */
      public NewTargetsProtos.NewTargetOrBuilder getNewTargetOrBuilder(
          int index) {
        if (newTargetBuilder_ == null) {
          return newTarget_.get(index);  } else {
          return newTargetBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .NewTarget newTarget = 1;</code>
       */
      public java.util.List<? extends NewTargetsProtos.NewTargetOrBuilder> 
           getNewTargetOrBuilderList() {
        if (newTargetBuilder_ != null) {
          return newTargetBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(newTarget_);
        }
      }
      /**
       * <code>repeated .NewTarget newTarget = 1;</code>
       */
      public NewTargetsProtos.NewTarget.Builder addNewTargetBuilder() {
        return getNewTargetFieldBuilder().addBuilder(
            NewTargetsProtos.NewTarget.getDefaultInstance());
      }
      /**
       * <code>repeated .NewTarget newTarget = 1;</code>
       */
      public NewTargetsProtos.NewTarget.Builder addNewTargetBuilder(
          int index) {
        return getNewTargetFieldBuilder().addBuilder(
            index, NewTargetsProtos.NewTarget.getDefaultInstance());
      }
      /**
       * <code>repeated .NewTarget newTarget = 1;</code>
       */
      public java.util.List<NewTargetsProtos.NewTarget.Builder> 
           getNewTargetBuilderList() {
        return getNewTargetFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          NewTargetsProtos.NewTarget, NewTargetsProtos.NewTarget.Builder, NewTargetsProtos.NewTargetOrBuilder> 
          getNewTargetFieldBuilder() {
        if (newTargetBuilder_ == null) {
          newTargetBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              NewTargetsProtos.NewTarget, NewTargetsProtos.NewTarget.Builder, NewTargetsProtos.NewTargetOrBuilder>(
                  newTarget_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          newTarget_ = null;
        }
        return newTargetBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:NewTargets)
    }

    static {
      defaultInstance = new NewTargets(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NewTargets)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NewTarget_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NewTarget_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NewTargets_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NewTargets_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020NewTargets.proto\"D\n\tNewTarget\022\030\n\020uniqu" +
      "eObjectName\030\001 \002(\t\022\r\n\005state\030\002 \002(\005\022\016\n\006targ" +
      "et\030\003 \002(\t\"+\n\nNewTargets\022\035\n\tnewTarget\030\001 \003(" +
      "\0132\n.NewTargetB\022B\020NewTargetsProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_NewTarget_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NewTarget_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_NewTarget_descriptor,
        new java.lang.String[] { "UniqueObjectName", "State", "Target", });
    internal_static_NewTargets_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_NewTargets_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_NewTargets_descriptor,
        new java.lang.String[] { "NewTarget", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
