# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Environment.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
#from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

#_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Environment.proto',
  package='',
  serialized_pb=_b('\n\x11\x45nvironment.proto\"]\n\x05Water\x12\x18\n\x10uniqueObjectName\x18\x01 \x02(\t\x12\x0c\n\x04posX\x18\x02 \x02(\x02\x12\x0c\n\x04posY\x18\x03 \x02(\x02\x12\x0e\n\x06scaleX\x18\x04 \x02(\x02\x12\x0e\n\x06scaleY\x18\x05 \x02(\x02\"b\n\nVegetation\x12\x18\n\x10uniqueObjectName\x18\x01 \x02(\t\x12\x0c\n\x04posX\x18\x02 \x02(\x02\x12\x0c\n\x04posY\x18\x03 \x02(\x02\x12\x0e\n\x06scaleX\x18\x04 \x02(\x02\x12\x0e\n\x06scaleY\x18\x05 \x02(\x02\"E\n\x12\x45nvironmentObjects\x12\x15\n\x05water\x18\x01 \x03(\x0b\x32\x06.Water\x12\x18\n\x03veg\x18\x02 \x03(\x0b\x32\x0b.VegetationB\x13\x42\x11\x45nvironmentProtos')
)
#_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_WATER = _descriptor.Descriptor(
  name='Water',
  full_name='Water',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uniqueObjectName', full_name='Water.uniqueObjectName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='posX', full_name='Water.posX', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='posY', full_name='Water.posY', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scaleX', full_name='Water.scaleX', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scaleY', full_name='Water.scaleY', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  #oneofs=[
  #],
  serialized_start=21,
  serialized_end=114,
)


_VEGETATION = _descriptor.Descriptor(
  name='Vegetation',
  full_name='Vegetation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uniqueObjectName', full_name='Vegetation.uniqueObjectName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='posX', full_name='Vegetation.posX', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='posY', full_name='Vegetation.posY', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scaleX', full_name='Vegetation.scaleX', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scaleY', full_name='Vegetation.scaleY', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  #oneofs=[
  #],
  serialized_start=116,
  serialized_end=214,
)


_ENVIRONMENTOBJECTS = _descriptor.Descriptor(
  name='EnvironmentObjects',
  full_name='EnvironmentObjects',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='water', full_name='EnvironmentObjects.water', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='veg', full_name='EnvironmentObjects.veg', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  #oneofs=[
  #],
  serialized_start=216,
  serialized_end=285,
)

_ENVIRONMENTOBJECTS.fields_by_name['water'].message_type = _WATER
_ENVIRONMENTOBJECTS.fields_by_name['veg'].message_type = _VEGETATION
DESCRIPTOR.message_types_by_name['Water'] = _WATER
DESCRIPTOR.message_types_by_name['Vegetation'] = _VEGETATION
DESCRIPTOR.message_types_by_name['EnvironmentObjects'] = _ENVIRONMENTOBJECTS

Water = _reflection.GeneratedProtocolMessageType('Water', (_message.Message,), dict(
  DESCRIPTOR = _WATER,
  __module__ = 'Environment_pb2'
  # @@protoc_insertion_point(class_scope:Water)
  ))
#_sym_db.RegisterMessage(Water)

Vegetation = _reflection.GeneratedProtocolMessageType('Vegetation', (_message.Message,), dict(
  DESCRIPTOR = _VEGETATION,
  __module__ = 'Environment_pb2'
  # @@protoc_insertion_point(class_scope:Vegetation)
  ))
#_sym_db.RegisterMessage(Vegetation)

EnvironmentObjects = _reflection.GeneratedProtocolMessageType('EnvironmentObjects', (_message.Message,), dict(
  DESCRIPTOR = _ENVIRONMENTOBJECTS,
  __module__ = 'Environment_pb2'
  # @@protoc_insertion_point(class_scope:EnvironmentObjects)
  ))
#_sym_db.RegisterMessage(EnvironmentObjects)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\021EnvironmentProtos'))
# @@protoc_insertion_point(module_scope)
